version: '3.7'
services:
  mariadb:
    image: marksugar/mariadb:10.2.22
    container_name: mariadb
    privileged: true
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/mariadb:/data/mariadb:rw
    environment:
      - MYSQL_DATABASE=jumpserver
      - MYSQL_USER=jumpserver
      - MYSQL_PASSWORD=ijumpasswd
    ports:
      - "3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
  redis:
    image: marksugar/redis:5.0.0
    container_name: redis
    restart: always
    network_mode: "host"
    privileged: true
    environment:
    - REDIS_CONF=on
    - REQUIRE_PASS=OTdmOWI4ZTM4NTY1M2M4OTZh
    - MASTER_AUTH=OTdmOWI4ZTM4NTY1M2M4OTZh
    - MAXCLIENTS_NUM=600
    - MAXMEMORY_SIZE=4096M
    volumes:
    - /etc/localtime:/etc/localtime:ro
#    - /etc/redis:/etc/redis
    - /data/redis/redis-data:/data/redis:Z
    - /data/redis/logs:/data/logs
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    depends_on:
      - mariadb

  jumpserver:
    image: marksugar/jump:jms-1.4.9-zh
    container_name: jumpserver
    restart: always
    network_mode: "host"
    privileged: true
    environment:
    - SECRET_KEY=SECRET_KEY
    - BOOTSTRAP_TOKEN=BOOTSTRAP_TOKEN
    - DB_NAME=jumpserver
    - DB_PASSWORD=ijumpasswd
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_USER=jumpserver
    - REDIS_PASSWORD=OTdmOWI4ZTM4NTY1M2M4OTZh
    - REDIS_HOST=127.0.0.1
    - REDIS_PORT=6379
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/jumpserver/media:/opt/jumpserver/data/media
    - /data/jumpserver/logs:/opt/jumpserver/logs
    - /data/jumpserver/data:/opt/jumpserver/data
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    depends_on:
      - mariadb
      - redis      

  guacamole:
    image: marksugar/jump:guacamole-0.9.14-zh
    container_name: guacamole
    restart: always
    network_mode: "host"
    privileged: true
    environment:
    - GPORT=8081
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/guacamole/logs:/config/tomcat/logs    
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    depends_on:
      - redis
      - mariadb
      - jumpserver

  coco:
    image: marksugar/jump:coco-1.4.9-zh
    container_name: coco
    restart: always
    network_mode: "host"
    privileged: true
    environment:
    - BOOTSTRAP_TOKEN=BOOTSTRAP_TOKEN
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/coco/data:/opt/coco/data:rw
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    depends_on:
      - redis
      - mariadb
      - jumpserver      
      - guacamole

  nginx_luna:
    image: marksugar/jump:nginx-luna-1.4.9-1.15.12-zh
    container_name: nginx_luna
    restart: always
    network_mode: "host"
    privileged: true
    environment:
    - R_LISTEN=localhost:8080
    - SERVER_NAME=_
    - SOCKER_DESCRIBE=localhost:5000
    - COCO_DESCRIBE=localhost:5000
    - GUACAMOLE_DESCRIBE=localhost:8081
    - LISTEN_PORT=80
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/jumpserver/data:/opt/jumpserver/data
    - /data/jumpserver/media:/opt/jumpserver/data/media    
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    depends_on:
      - redis
      - mariadb
      - jumpserver
      - guacamole
      - coco
