version: '2'
services:
  php-fpm:
    build: 
      context: https://raw.githubusercontent.com/LinuxEA-Mark/docker-nginx-php-fpm/master/php-5.6.29_modules_redis_swoole/Dockerfile
    container_name: php-fpm
    restart: always
    network_mode: "host"
    volumes:
    - /data/docker/php-fpm/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
    - /data/docker/php-fpm/php.ini:/usr/local/php/lib/php.ini
    - /data/logs/php-fpm:/logs
    - /data/wwwroot:/data/wwwroot
