version: '2'
services:
  svb:
    image: marksugar/svn
#    build:
#        context: https://raw.githubusercontent.com/LinuxEA-Mark/docker-subversion1.9.4/master/Dockerfile
    container_name: svn
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /data/docker/subversion:/data/docker/svn/
