version: '2'
services:
  jumpserver0.3.2:
    build:
       context: https://raw.githubusercontent.com/LinuxEA-Mark/docker-jumpserver/master/Dockerfile
    container_name: jumpserver
    restart: always
    network_mode: "host"
    volumes:
      - /data/jumpserver/jumpserver.conf:/jumpserver/jumpserver.conf
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
      - /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    ports:
      - "8888:80"
      - "2222:22"
    environment:
       - USE_MYSQL=true
       - MYSQL_ENGINE=mysql
       - MYSQL_HOST=127.0.0.1
       - MYSQL_PORT=3306
       - MYSQL_USER=jumpserver
       - MYSQL_PASS=password
       - MYSQL_NAME=jumpserver
       - USE_MAIL=true
       - MAIL_ENABLED=1
       - MAIL_HOST=smtp.163.com
       - MAIL_PORT=25
       - MAIL_USER=usertzc@163.com
       - MAIL_PASS=
       - MAIL_USE_TLS=False
       - MAIL_USE_SSL=False
