version: '2'
services:
  php-fpm:
    image: marksugar/php-fpm:5.6.38
#    build: 
#      context: https://raw.githubusercontent.com/LinuxEA-Mark/docker-alpine-php/master/php-5.6.38/Dockerfile
    container_name: php-fpm
    restart: always
    network_mode: "host"
    volumes:
    - /usr/local/php/etc/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
    - /usr/local/php/etc/php.ini:/usr/local/php/lib/php.ini
    - /data/logs/php-fpm:/logs
    - /data/wwwroot:/data/wwwroot
