version: '2'
services:
  haproxy:
    build:
      context: https://raw.githubusercontent.com/LinuxEA-Mark/HAproxy/master/Dockerfile
    container_name: haproxy
    restart: always
    network_mode: "host"
    volumes: 
        - /data/ha/haproxy.cfg:/etc/haproxy/haproxy.cfg
