version: '3'
services:
  nginx:
    image: marksugar/nginx:1.14.0-2
#    build: .
#      context: https://raw.githubusercontent.com/LinuxEA-Mark/docker-alpine-nginx-php/master/nginx_1.14.0/Dockerfile
    container_name: nginx
    restart: always
    network_mode: "host"
    volumes:
      - /etc/nginx:/etc/nginx
      - /data/wwwroot:/data/wwwroot
      - /data/wwwlogs:/data/wwwlogs
    ports:
      - "80"
